ALTER TABLE IF EXISTS SOURCE DROP CONSTRAINT COURSE_CATEGORY_FK;
ALTER TABLE IF EXISTS SOURCE DROP CONSTRAINT COURSE_SOURCE_FK;

DROP TABLE IF EXISTS SOURCE;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS COURSE;

CREATE TABLE SOURCE
(
  source_id    BIGSERIAL           NOT NULL,
  source_name  VARCHAR(150)        NOT NULL,
  source_link  VARCHAR(150)        NOT NULL
);
ALTER TABLE SOURCE
  ADD CONSTRAINT SOURCE_PK PRIMARY KEY (source_id);

CREATE TABLE CATEGORY
(
  category_id    BIGSERIAL         NOT NULL,
  category_name  VARCHAR(50)       NOT NULL
);
ALTER TABLE CATEGORY
  ADD CONSTRAINT CATEGORY_PK PRIMARY KEY (category_id);

CREATE TABLE COURSE
(
  course_id    BIGSERIAL         NOT NULL,
  course_name  VARCHAR(50)       NOT NULL,
  description  TEXT,
  start_time   TIMESTAMP,
  end_time     TIMESTAMP,
  category_id  BIGINT,
  source_id    BIGINT
);
ALTER TABLE COURSE
  ADD CONSTRAINT COURSE_PK PRIMARY KEY (course_id);


ALTER TABLE COURSE
  ADD CONSTRAINT COURSE_CATEGORY_FK FOREIGN KEY (course_id) REFERENCES CATEGORY (category_id) ON DELETE CASCADE;

ALTER TABLE COURSE
  ADD CONSTRAINT COURSE_SOURCE_FK FOREIGN KEY (course_id) REFERENCES SOURCE (source_id) ON DELETE CASCADE;